### ISSUE TITLE
spdx-CycloneDX conversion issue: simple-to-decide spdx-document-creation-fields

### ISSUE THREAD

**Issue by dn-scribe** [bom-squad/protobom#34]
[**SPDX document creation information section**](https://spdx.github.io/spdx-spec/v2.3/document-creation-information/)
[specVersion](https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#61-spdx-version-field)

 - spdx.specVersion = config.spdx.specVersion, default to "SPDX-2.3"
 - translationNotes.cycloneDX.bomFormat = cycloneDX.bomFormat
 - translationNotes.cycloneDX.specVersion = cycloneDX.specVersion

Links:

 - [bomFormat](https://cyclonedx.org/docs/1.4/json/#bomFormat)
 - [specVersion](https://cyclonedx.org/docs/1.4/json/#specVersion)

[**DataLicense**](https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#62-data-license-field)
 - spdx.dataLicense = "CC0-1.0"

Verification: spdx.dataLicense == "CC0-1.0"

Note: one could consider taking data from cycloneDX->metadata->licenses. As I understand it, this cycloneDX is about the artrifact licenses, while the spdx.dataLicnese is about the license of the data in the SBOM.

[**License list version**](https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#67-license-list-version-field)
 - spdx.licenseListVersion = config.spdx.licenseListVersion, default to not including this element at all.

Notes:

Future feature: May be calculated from license info present in ths CycloneDX

[**Created**](https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#69-created-field)
 - spdx.created = conversion time if config.spdx.created == "conversion_time", or default to this if no config is provided.
 - spdx.created = cycloneDX.metadata.timeStamp if config.spdx.created == "original_time"

Notes:

consider a global setting (for spdx.created and cycloneDX.metadata.timeStamp)
Check if cycloneDX dictates a time-date structure and handle the case that it does not.
Verification: Verify time is UTC formatted.

[**Creator Comment**](https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#610-creator-comment-field)
 - spdx.creatorComment = config.spdx.creatorComment, default none (do not include field).

[**Document Comment**](https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#611-document-comment-field)
 - if config.spdx.documentCommentSetting == "config" then spdx.documentComment = config.spdx.documentComment
 - if config.spdx.documentCommentSetting == "allCycloneDX" then spdx.documentComment = cycloneDX
consider: store as base64 or compressed JSON
 - if config.spdx.documentCommentSetting == "CycloneDXMetadata" then spdx.documentComment = cycloneDX.metadata

Notes:

 - Storing the whole cycloneDX can enable translation round trips. It may cause problems for spdx viewers, since probably this field is supposed to be displayed.
 - Consider: instead to the suggestion - only support a user provided field, default to none (do not include the field).

**Comment by puerco** [comment]
OK I mostly agree with these, just a couple of comments:

**licenseListVersion:**
This one should be fixed to the version of the SPDX license we use to validate the license identifiers. Validating them is a process that will need to be done (related to https://github.com/bom-squad/protobom/issues/38 ). In order to ensure license ids are valid you need to check with a specific version. For example in `bom` [we embed the latest SPDX license list](https://github.com/kubernetes-sigs/bom/blob/57a436d9a475952692f6b828b45236e01ba74ca3/magefile.go#L310-L312) to make it available to the license catalog. We could do something similar here or use that module if we need it.

**Document Comment**
I don't agree with this one. Embedding one SBOM into the comments field of another means modifying the SBOM data and it should not be done. The [comments of the protobom document](https://github.com/bom-squad/protobom/blob/d56806732603e3d147375f1f2fa33d9d0724ef8d/api/sbom.proto#L62) should be rendered as they are into the equivalent comments field of each format we serialize to. If the tool will be capable of spitting out a machine readable translation report, that would be the place to store it. 

Keep in mind that preserving the original document is of little value as is roundtripping to the original format as proof of anything. All ingestion is lossless so, in theory, any protobom that originated from a specific format should be able to be rendered into that format without any data loss. For example: if I have a protobom whose data came from a CycloneDX 1.5 document, I should be able to serialize it to CycloneDX 1.5 without losing anything.
